server:
  port: 8001
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: optional:secrets.yaml








