
spring:
  config:
    import: secrets.yaml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update







